const axios = require("axios");
const fs = require("fs/promises");
const path = require("path");

let companies = [
  "20MICRONS",
  "21STCENMGM",
  "360ONE",
  "3IINFOLTD",
  "3MINDIA",
  "3PLAND",
  "5PAISA",
  "63MOONS",
  "A2ZINFRA",
  "AAATECH",
  "AAKASH",
  "AAREYDRUGS",
  "AARON",
  "AARTECH",
  "AARTIDRUGS",
  "AARTIIND",
  "AARTIPHARM",
  "AARTISURF",
  "AARVEEDEN",
  "AARVI",
  "AAVAS",
  "ABAN",
  "ABB",
  "ABBOTINDIA",
  "ABCAPITAL",
  "ABFRL",
  "ABMINTLLTD",
  "ABSLAMC",
  "ACC",
  "ACCELYA",
  "ACCURACY",
  "ACE",
  "ACEINTEG",
  "ACI",
  "ACL",
  "ADANIENSOL",
  "ADANIENT",
  "ADANIGREEN",
  "ADANIPORTS",
  "ADANIPOWER",
  "ADFFOODS",
  "ADL",
  "ADORWELD",
  "ADROITINFO",
  "ADSL",
  "ADVANIHOTR",
  "ADVENZYMES",
  "AEGISCHEM",
  "AEROFLEX",
  "AETHER",
  "AFFLE",
  "AGARIND",
  "AGI",
  "AGRITECH",
  "AGROPHOS",
  "AGSTRA",
  "AHL",
  "AHLADA",
  "AHLEAST",
  "AHLUCONT",
  "AIAENG",
  "AIRAN",
  "AIROLAM",
  "AJANTPHARM",
  "AJMERA",
  "AJOONI",
  "AKASH",
  "AKG",
  "AKI",
  "AKSHAR",
  "AKSHARCHEM",
  "AKSHOPTFBR",
  "AKZOINDIA",
  "ALANKIT",
  "ALBERTDAVD",
  "ALEMBICLTD",
  "ALICON",
  "ALKALI",
  "ALKEM",
  "ALKYLAMINE",
  "ALLCARGO",
  "ALLSEC",
  "ALMONDZ",
  "ALOKINDS",
  "ALPA",
  "ALPHAGEO",
  "ALPSINDUS",
  "AMARAJABAT",
  "AMBER",
  "AMBICAAGAR",
  "AMBIKCO",
  "AMBUJACEM",
  "AMDIND",
  "AMIORG",
  "AMJLAND",
  "AMRUTANJAN",
  "ANANDRATHI",
  "ANANTRAJ",
  "ANDHRAPAP",
  "ANDHRSUGAR",
  "ANDREWYU",
  "ANGELONE",
  "ANIKINDS",
  "ANKITMETAL",
  "ANMOL",
  "ANSALAPI",
  "ANTGRAPHIC",
  "ANUP",
  "ANURAS",
  "APARINDS",
  "APCL",
  "APCOTEXIND",
  "APEX",
  "APLAPOLLO",
  "APLLTD",
  "APOLLO",
  "APOLLOHOSP",
  "APOLLOPIPE",
  "APOLLOTYRE",
  "APOLSINHOT",
  "APTECHT",
  "APTUS",
  "ARCHIDPLY",
  "ARCHIES",
  "ARENTERP",
  "ARIES",
  "ARIHANTCAP",
  "ARIHANTSUP",
  "ARMANFIN",
  "AROGRANITE",
  "ARROWGREEN",
  "ARSHIYA",
  "ARSSINFRA",
  "ARTEMISMED",
  "ARTNIRMAN",
  "ARVEE",
  "ARVIND",
  "ARVINDFASN",
  "ARVSMART",
  "ASAHIINDIA",
  "ASAHISONG",
  "ASAL",
  "ASALCBR",
  "ASHAPURMIN",
  "ASHIANA",
  "ASHIMASYN",
  "ASHOKA",
  "ASHOKAMET",
  "ASHOKLEY",
  "ASIANENE",
  "ASIANHOTNR",
  "ASIANPAINT",
  "ASIANTILES",
  "ASMS",
  "ASPINWALL",
  "ASTEC",
  "ASTERDM",
  "ASTRAL",
  "ASTRAMICRO",
  "ASTRAZEN",
  "ASTRON",
  "ATALREAL",
  "ATAM",
  "ATFL",
  "ATGL",
  "ATL",
  "ATLANTA",
  "ATUL",
  "ATULAUTO",
  "AUBANK",
  "AURIONPRO",
  "AUROPHARMA",
  "AURUM",
  "AUSOMENT",
  "AUTOAXLES",
  "AUTOIND",
  "AVADHSUGAR",
  "AVALON",
  "AVANTIFEED",
  "AVG",
  "AVONMORE",
  "AVROIND",
  "AVTNPL",
  "AWHCL",
  "AWL",
  "AXISBANK",
  "AXISCADES",
  "AXITA",
  "AYMSYNTEX",
  "BAGFILMS",
  "BAIDFIN",
  "BAJAJ-AUTO",
  "BAJAJCON",
  "BAJAJELEC",
  "BAJAJFINSV",
  "BAJAJHCARE",
  "BAJAJHIND",
  "BAJAJHLDNG",
  "BAJFINANCE",
  "BALAJITELE",
  "BALAMINES",
  "BALAXI",
  "BALKRISHNA",
  "BALKRISIND",
  "BALMLAWRIE",
  "BALPHARMA",
  "BALRAMCHIN",
  "BANARBEADS",
  "BANARISUG",
  "BANCOINDIA",
  "BANDHANBNK",
  "BANG",
  "BANKA",
  "BANKBARODA",
  "BANKINDIA",
  "BANSWRAS",
  "BARBEQUE",
  "BASF",
  "BASML",
  "BATAINDIA",
  "BAYERCROP",
  "BBL",
  "BBOX",
  "BBTC",
  "BBTCL",
  "BCG",
  "BCLIND",
  "BCONCEPTS",
  "BDL",
  "BEARDSELL",
  "BECTORFOOD",
  "BEDMUTHA",
  "BEL",
  "BEML",
  "BEPL",
  "BERGEPAINT",
  "BFINVEST",
  "BFUTILITIE",
  "BGRENERGY",
  "BHAGCHEM",
  "BHAGERIA",
  "BHAGYANGR",
  "BHANDARI",
  "BHARATFORG",
  "BHARATGEAR",
  "BHARATRAS",
  "BHARATWIRE",
  "BHARTIARTL",
  "BHEL",
  "BIGBLOC",
  "BIKAJI",
  "BIL",
  "BINANIIND",
  "BIOCON",
  "BIOFILCHEM",
  "BIRLACABLE",
  "BIRLACORPN",
  "BIRLAMONEY",
  "BKMINDST",
  "BLAL",
  "BLBLIMITED",
  "BLISSGVS",
  "BLKASHYAP",
  "BLS",
  "BLUECHIP",
  "BLUECOAST",
  "BLUEDART",
  "BLUESTAR",
];

const baseApiUrl = "https://www.nseindia.com/api/quote-equity?symbol=";
const fetchInterval = 0;
let currentIndex = 0;
const restartinterval = 10000;

async function fetchDataAndSave() {
  const folderName = "company";
  try {
    await fs.mkdir(folderName);
  } catch (err) {
    if (err.code !== "EEXIST") {
      console.error(`Error creating folder: ${err.message}`);
      return;
    }
  }

  const companyName = companies[currentIndex]; // Get the current company
  try {
    const apiUrl = `${baseApiUrl}${companyName}`;
    const apiUrl2 = `https://www.nseindia.com/api/quote-equity?symbol=${companyName}&section=trade_info`;
    const response = await axios.get(apiUrl, {
      headers: {
        Cookie: `_ga=GA1.1.367523999.1694345405; AKA_A2=A; nsit=y95zlR_BQDPIUm7Ej0Xly8F8; bm_mi=1D838F3D3EB6BD6765B2013A449776DC~YAAQjbYRYL+H8Y+KAQAAqGDPoxXSua03nggg9YCx/1AE1kYrnqZfG2lUPzd544wu3SHql1Yieo38R+Cc9XmMh+GCn8wvvZPYrzRCde2QKhwG6mkjFaOFlB0WrQg5FBv0eSD1ZLW2FOTx3WsoMijZKb2eifkAZo5f1Zu+z7tV95MBgSrnaTDvDU4h2g1e5OGg3UZEyHeM7oK3mV963c4v+7eMTJUymROASzZuXqiHusrFxHISP10X/uDJuQLj/Fk8JUea7HKm29WaQ0WM8ymSoqYYwfJkAcyeePc0fmha08TbsKMoNn25ayXI8JlKid4=~1; defaultLang=en; nseQuoteSymbols=[{"symbol":"TATACONSUM","identifier":null,"type":"equity"}]; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTY5NDk2NTQyNSwiZXhwIjoxNjk0OTcyNjI1fQ.ZVhmfpTcjTLF3gyuzqXp_Wj1OKQMid2lKscFzzqD2Bc; ak_bmsc=AB1C8CFD4D75575BCC9D1906C14E8DCE~000000000000000000000000000000~YAAQjbYRYBeQ8Y+KAQAAKebPoxVosRIcErOCWuiWft42iWO/ohDEdoNgr1LSxg/5ZHvn05Tx+NlktnyKNK2rDN8txu0FyE5rpMhI0+iO0FLpff7/DHWbGjDS5XGcnuwjw9+yzh6VUZfrsFZjJZREGR9p3aeQWpuMVgssBArB9mR0hdOeYbjGJ+4EmHHuoPysxWtRowCPIdhCHvlvhfADBTVfeiv3GAjK4rqT544L5MYFdZ9XJA8w/ZZYwnS4K9r2JutulifOnsbagp0mODiFp0WLE31hneA3I6KsG4FamaZnev9qUO+2+UfpNKe4RBAJ0zsD5Mut/emLxGOdVR5Iip3YbzonA10Zag9ieQqNH3x2rsPLeGDrc8CNua0yFqAt03ae0o9GSdBPcunvHdHtWeY/ijCV/SwLTBkhlAsFZrjW2Wbz9ZehTGIgODYZEQPo7LfPeKIEBL9el4t7NuH2hxNRns+GA3ibPOy88Grl//a52nqrWfw6RYxloOpSq8zqbuxBzUEr8SNJuJ6bLQy6bgols2/W9A+PW5SzsWgYOAuPmPNu; RT="z=1&dm=nseindia.com&si=edc18d86-3ea9-46a2-9e1c-0aa5556f2d9d&ss=lmnmmodv&sl=3&se=8c&tt=3ma&bcn=%2F%2F684d0d4a.akstat.io%2F"; bm_sv=3AED692A3AA5C5F1B36729E599B4E852~YAAQjbYRYDWQ8Y+KAQAAm+jPoxWRqraubAaBeVx9vAEi6/1ewIQRCDJpy2LmFcbKwsx+jWt0PbddQG60jZCLrvrngeGuNiJAii+o39gnlCdIFkjxVChXEYxdSRG7bvvFk7p7ceGEF59Xkx6TVyJXA1WlSrBuV6uACgf0PQ/TALEC/CJPlzYvrBxOJC2nVrf4qtT/bzobFCmAuAzURBVNdEZL4D9mEtAzeIw45uws47nEaVUcWC5vLqAtgO1DKqGm8mH2~1; _ga_PJSKY6CFJH=GS1.1.1694965391.2.1.1694965424.27.0.0`,
        timeout: 2000,
      },
    });
    const response2 = await axios.get(apiUrl2, {
        headers: {
          Cookie: `_ga=GA1.1.367523999.1694345405; AKA_A2=A; nsit=y95zlR_BQDPIUm7Ej0Xly8F8; bm_mi=1D838F3D3EB6BD6765B2013A449776DC~YAAQjbYRYL+H8Y+KAQAAqGDPoxXSua03nggg9YCx/1AE1kYrnqZfG2lUPzd544wu3SHql1Yieo38R+Cc9XmMh+GCn8wvvZPYrzRCde2QKhwG6mkjFaOFlB0WrQg5FBv0eSD1ZLW2FOTx3WsoMijZKb2eifkAZo5f1Zu+z7tV95MBgSrnaTDvDU4h2g1e5OGg3UZEyHeM7oK3mV963c4v+7eMTJUymROASzZuXqiHusrFxHISP10X/uDJuQLj/Fk8JUea7HKm29WaQ0WM8ymSoqYYwfJkAcyeePc0fmha08TbsKMoNn25ayXI8JlKid4=~1; defaultLang=en; nseQuoteSymbols=[{"symbol":"TATACONSUM","identifier":null,"type":"equity"}]; nseappid=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkubnNlIiwiYXVkIjoiYXBpLm5zZSIsImlhdCI6MTY5NDk2NTQyNSwiZXhwIjoxNjk0OTcyNjI1fQ.ZVhmfpTcjTLF3gyuzqXp_Wj1OKQMid2lKscFzzqD2Bc; ak_bmsc=AB1C8CFD4D75575BCC9D1906C14E8DCE~000000000000000000000000000000~YAAQjbYRYBeQ8Y+KAQAAKebPoxVosRIcErOCWuiWft42iWO/ohDEdoNgr1LSxg/5ZHvn05Tx+NlktnyKNK2rDN8txu0FyE5rpMhI0+iO0FLpff7/DHWbGjDS5XGcnuwjw9+yzh6VUZfrsFZjJZREGR9p3aeQWpuMVgssBArB9mR0hdOeYbjGJ+4EmHHuoPysxWtRowCPIdhCHvlvhfADBTVfeiv3GAjK4rqT544L5MYFdZ9XJA8w/ZZYwnS4K9r2JutulifOnsbagp0mODiFp0WLE31hneA3I6KsG4FamaZnev9qUO+2+UfpNKe4RBAJ0zsD5Mut/emLxGOdVR5Iip3YbzonA10Zag9ieQqNH3x2rsPLeGDrc8CNua0yFqAt03ae0o9GSdBPcunvHdHtWeY/ijCV/SwLTBkhlAsFZrjW2Wbz9ZehTGIgODYZEQPo7LfPeKIEBL9el4t7NuH2hxNRns+GA3ibPOy88Grl//a52nqrWfw6RYxloOpSq8zqbuxBzUEr8SNJuJ6bLQy6bgols2/W9A+PW5SzsWgYOAuPmPNu; RT="z=1&dm=nseindia.com&si=edc18d86-3ea9-46a2-9e1c-0aa5556f2d9d&ss=lmnmmodv&sl=3&se=8c&tt=3ma&bcn=%2F%2F684d0d4a.akstat.io%2F"; bm_sv=3AED692A3AA5C5F1B36729E599B4E852~YAAQjbYRYDWQ8Y+KAQAAm+jPoxWRqraubAaBeVx9vAEi6/1ewIQRCDJpy2LmFcbKwsx+jWt0PbddQG60jZCLrvrngeGuNiJAii+o39gnlCdIFkjxVChXEYxdSRG7bvvFk7p7ceGEF59Xkx6TVyJXA1WlSrBuV6uACgf0PQ/TALEC/CJPlzYvrBxOJC2nVrf4qtT/bzobFCmAuAzURBVNdEZL4D9mEtAzeIw45uws47nEaVUcWC5vLqAtgO1DKqGm8mH2~1; _ga_PJSKY6CFJH=GS1.1.1694965391.2.1.1694965424.27.0.0`,
          timeout: 2000,
        },
      });
    const companyData = {
      time: new Date().toLocaleString(),
      ...response.data,
      ...response2.data,
    };
    const fileName = path.join(folderName, `${companyName}.json`);
    let existingData = [];
    try {
      const fileData = await fs.readFile(fileName, "utf-8");
      existingData = JSON.parse(fileData);
    } catch (err) {}
    existingData.push(companyData);
    await fs.writeFile(fileName, JSON.stringify(existingData, null, 2));
    console.log(`Data for ${companyName} saved to ${fileName}`);
  } catch (error) {
    console.error(`Error fetching data for ${companyName}: ${error.message}`);
    console.log("Will restart after " + restartinterval / 1000 + " Second");
  }

  // Increment the index and handle looping back to the start
  currentIndex = (currentIndex + 1) % companies.length;

  setTimeout(fetchDataAndSave, fetchInterval);
}

function startFetchingLoop() {
  fetchDataAndSave();
}

startFetchingLoop();
